### ISSUE TITLE
Not working for FoR dataset

### ISSUE THREAD

**Issue by utkarsh-tyagi** [ghuawhu/end-to-end-synthetic-speech-detection#1]
Hi ghuawhu ,

Thanks for providing the pre-trained model but I have tested your model for FoR dataset by aptly lab and it is not working at all!

EER = 44 % for eval dataset
Accuracy = 48.64 %
could you please tell me what is the reason behind this and model is working fine for the asvspoof2019 dataset but when I tested for the new or unseen dataset, it is not working as expected?

Also , please provide me your email id for further contact.

Thanks,
Utkarsh

**Comment by ghua-ac** [comment]
> Hi ghuawhu ,
> 
> Thanks for providing the pre-trained model but I have tested your model for FoR dataset by aptly lab and it is not working at all!
> 
> EER = 44 % for eval dataset
> Accuracy = 48.64 %
> could you please tell me what is the reason behind this and model is working fine for the asvspoof2019 dataset but when I tested for the new or unseen dataset, it is not working as expected?
> 
> Also , please provide me your email id for further contact.
> 
> Thanks,
> Utkarsh

Hi Utkarsh,

Thank you for your inquiry.
Our experiments were carried out solely on ASVspoof 19 and 15 datasets, which follows what has been reported in the majority of the existing works, while we haven't tried additional cross-dataset testing like what you have done.

Based on your results, it seems that the proposed models have problem in overall generalization, though they can generalize within the ASVspoof setting. 

We have noted this issue and are working towards improving the current models.

Thank you again.

Best wishes,
Guang HUA

**Comment by utkarsh-tyagi** [comment]
Thanks for your response!
